Ported mgmtsystem_action
Fix typo and pep8

Changes made for API v8

Removed pdb lines

Removed vim lines and fixed domain

Removed comments and commented code

Added tests and updated code to v8

Fix flake8 errors

Updated according to reviews

Removed case_close

It is used and only contains things from mgmtsystem_nonconformity

Removed blank line, flake8 not happy

Removed check for user_id as user_id cannot be null

When doing `case.user_id = None`, it will throw this error:

    IntegrityError: null value in column "partner_id" violates not-null
    constraint

Remove transition case_close and moved icon