Create change
GitHub Pull Request: https://api.github.com/repos/OCA/management-system/pulls/51

8.0 mgmtsystem review

Depends on 

- [x] #30 

- [x] #25 

Patch-set: 1
Change-id: I1c916f781bdf15c955d830383991cf6371205c7a
Subject: [FIX] AttributeError: 'module' object has no attribute 'Many2Many'
Branch: refs/heads/8.0
Commit: 9a7e437e8a2f18e13819588fbe69948b88498a94
Groups: 0eec9dd288b9c0db70a89ef23a648cf7e9d6d8b0